# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lawyer.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerModel',
            fields=[
                ('id_laywer', models.AutoField(db_column='id_laywer', primary_key=True, serialize=False, verbose_name='Cod Laywer')),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(db_column='phone', max_length=14, validators=[lawyer.utils.validate_phone], verbose_name='Telefone')),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[lawyer.utils.validate_cpf])),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Atualizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Criado em')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Descricao')),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Advogado',
                'verbose_name_plural': 'Advogados',
                'db_table': 'lawyer',
                'ordering': ['-created_at'],
            },
        ),
    ]
